
@room_id = {{get_rooms.response.body.rooms[0].id}}
@message_id = "10459b5b-ac6e-4fb1-9b1f-17ff06b15252"

# @name get_rooms
GET http://localhost:8080/api/rooms

###

# @name create_room
POST http://localhost:8080/api/rooms
content-type: application/json

{
    "theme": "teste 1"
}

###

# @name subscribe_to_room
GET http://localhost:8080/subscribe/{{room_id}}

###

# @name create_message
POST http://localhost:8080/api/rooms/{{room_id}}/messages
Content-Type: application/json

{
    "message": "Teste"
}

###

# @name get_room_messages
GET http://localhost:8080/api/rooms/{{room_id}}/messages

###

# @name get_message
GET http://localhost:8080/api/rooms/{{room_id}}/messages/{{message_id}}

###

# @name react_to_message
PATCH http://localhost:8080/api/rooms/{{room_id}}/messages/{{message_id}}/react

###

# @name remove_reaction_from_message
DELETE  http://localhost:8080/api/rooms/{{room_id}}/messages/{{message_id}}/react

###

# @name answer_message
PATCH http://localhost:8080/api/rooms/{{room_id}}/messages/{{message_id}}/answer
